// Do not edit.  Generated by cheby 1.7.dev0 using these options:
//  --hdl verilog --gen-hdl gpio_regs.v --input gpio_regs.yaml
// Generated on Sun Feb 15 20:11:42 2026 by akiel



module gpio_regs
  (
    input   wire pclk,
    input   wire presetn,
    input   wire [2:2] paddr,
    input   wire psel,
    input   wire pwrite,
    input   wire penable,
    output  wire pready,
    input   wire [31:0] pwdata,
    input   wire [3:0] pstrb,
    output  wire [31:0] prdata,
    output  wire pslverr,

    // REG out
    output  wire [31:0] out_o,

    // REG stat
    input   wire [31:0] stat_i
  );
  wire wr_req;
  wire [2:2] wr_addr;
  wire [31:0] wr_data;
  wire rd_req;
  wire [2:2] rd_addr;
  reg [31:0] rd_data;
  reg wr_ack;
  reg rd_ack;
  reg [31:0] out_reg;
  reg out_wreq;
  wire out_wack;
  reg rd_ack_d0;
  reg [31:0] rd_dat_d0;
  reg wr_req_d0;
  reg [2:2] wr_adr_d0;
  reg [31:0] wr_dat_d0;

  // Write Channel
  assign wr_req = (psel & pwrite) & ~penable;
  assign wr_addr = paddr;
  assign wr_data = pwdata;
  always @(pstrb)
  ;

  // Read Channel
  assign rd_req = (psel & ~pwrite) & ~penable;
  assign rd_addr = paddr;
  assign prdata = rd_data;
  assign pready = wr_ack | rd_ack;
  assign pslverr = 1'b0;

  // pipelining for wr-in+rd-out
  always @(posedge(pclk))
  begin
    if (!presetn)
      begin
        rd_ack <= 1'b0;
        rd_data <= 32'b00000000000000000000000000000000;
        wr_req_d0 <= 1'b0;
        wr_adr_d0 <= 1'b0;
        wr_dat_d0 <= 32'b00000000000000000000000000000000;
      end
    else
      begin
        rd_ack <= rd_ack_d0;
        rd_data <= rd_dat_d0;
        wr_req_d0 <= wr_req;
        wr_adr_d0 <= wr_addr;
        wr_dat_d0 <= wr_data;
      end
  end

  // Register out
  assign out_o = out_reg;
  assign out_wack = out_wreq;
  always @(posedge(pclk))
  begin
    if (!presetn)
      out_reg <= 32'b00000000000000000000000000000000;
    else
      if (out_wreq == 1'b1)
        out_reg <= wr_dat_d0;
  end

  // Register stat

  // Process for write requests.
  always @(wr_adr_d0, wr_req_d0, out_wack)
  begin
    out_wreq = 1'b0;
    case (wr_adr_d0[2:2])
    1'b0:
      begin
        // Reg out
        out_wreq = wr_req_d0;
        wr_ack = out_wack;
      end
    1'b1:
      // Reg stat
      wr_ack = wr_req_d0;
    default:
      wr_ack = wr_req_d0;
    endcase
  end

  // Process for read requests.
  always @(rd_addr, rd_req, out_reg, stat_i)
  begin
    // By default ack read requests
    rd_dat_d0 = {32{1'bx}};
    case (rd_addr[2:2])
    1'b0:
      begin
        // Reg out
        rd_ack_d0 = rd_req;
        rd_dat_d0 = out_reg;
      end
    1'b1:
      begin
        // Reg stat
        rd_ack_d0 = rd_req;
        rd_dat_d0 = stat_i;
      end
    default:
      rd_ack_d0 = rd_req;
    endcase
  end
endmodule
