// Do not edit.  Generated by cheby 1.7.dev0 using these options:
//  --hdl verilog --gen-hdl src/sysinfo_regs.v --input sysinfo_regs.yaml
// Generated on Mon Feb 16 10:44:57 2026 by akiel



module sysinfo_regs
  (
    input   wire pclk,
    input   wire presetn,
    input   wire [4:2] paddr,
    input   wire psel,
    input   wire pwrite,
    input   wire penable,
    output  wire pready,
    input   wire [31:0] pwdata,
    input   wire [3:0] pstrb,
    output  wire [31:0] prdata,
    output  wire pslverr,

    // REG magic
    input   wire [31:0] magic_i,

    // REG mfg_code_A
    input   wire [31:0] mfg_code_A_i,

    // REG mfg_code_B
    input   wire [31:0] mfg_code_B_i,

    // REG version
    input   wire [7:0] version_patch_i,
    input   wire [7:0] version_minor_i,
    input   wire [15:0] version_major_i,

    // REG cheby_version
    input   wire [7:0] cheby_version_patch_i,
    input   wire [7:0] cheby_version_minor_i,
    input   wire [15:0] cheby_version_major_i
  );
  wire wr_req;
  wire [4:2] wr_addr;
  wire rd_req;
  wire [4:2] rd_addr;
  reg [31:0] rd_data;
  reg wr_ack;
  reg rd_ack;
  reg rd_ack_d0;
  reg [31:0] rd_dat_d0;
  reg wr_req_d0;
  reg [4:2] wr_adr_d0;

  // Write Channel
  assign wr_req = (psel & pwrite) & ~penable;
  assign wr_addr = paddr;
  always @(pstrb)
  ;

  // Read Channel
  assign rd_req = (psel & ~pwrite) & ~penable;
  assign rd_addr = paddr;
  assign prdata = rd_data;
  assign pready = wr_ack | rd_ack;
  assign pslverr = 1'b0;

  // pipelining for wr-in+rd-out
  always @(posedge(pclk))
  begin
    if (!presetn)
      begin
        rd_ack <= 1'b0;
        rd_data <= 32'b00000000000000000000000000000000;
        wr_req_d0 <= 1'b0;
        wr_adr_d0 <= 3'b000;
      end
    else
      begin
        rd_ack <= rd_ack_d0;
        rd_data <= rd_dat_d0;
        wr_req_d0 <= wr_req;
        wr_adr_d0 <= wr_addr;
      end
  end

  // Register magic

  // Register mfg_code_A

  // Register mfg_code_B

  // Register version

  // Register cheby_version

  // Process for write requests.
  always @(wr_adr_d0, wr_req_d0)
  case (wr_adr_d0[4:2])
  3'b000:
    // Reg magic
    wr_ack = wr_req_d0;
  3'b001:
    // Reg mfg_code_A
    wr_ack = wr_req_d0;
  3'b010:
    // Reg mfg_code_B
    wr_ack = wr_req_d0;
  3'b011:
    // Reg version
    wr_ack = wr_req_d0;
  3'b100:
    // Reg cheby_version
    wr_ack = wr_req_d0;
  default:
    wr_ack = wr_req_d0;
  endcase

  // Process for read requests.
  always @(rd_addr, rd_req, magic_i, mfg_code_A_i, mfg_code_B_i, version_patch_i, version_minor_i, version_major_i, cheby_version_patch_i, cheby_version_minor_i, cheby_version_major_i)
  begin
    // By default ack read requests
    rd_dat_d0 = {32{1'bx}};
    case (rd_addr[4:2])
    3'b000:
      begin
        // Reg magic
        rd_ack_d0 = rd_req;
        rd_dat_d0 = magic_i;
      end
    3'b001:
      begin
        // Reg mfg_code_A
        rd_ack_d0 = rd_req;
        rd_dat_d0 = mfg_code_A_i;
      end
    3'b010:
      begin
        // Reg mfg_code_B
        rd_ack_d0 = rd_req;
        rd_dat_d0 = mfg_code_B_i;
      end
    3'b011:
      begin
        // Reg version
        rd_ack_d0 = rd_req;
        rd_dat_d0[7:0] = version_patch_i;
        rd_dat_d0[15:8] = version_minor_i;
        rd_dat_d0[31:16] = version_major_i;
      end
    3'b100:
      begin
        // Reg cheby_version
        rd_ack_d0 = rd_req;
        rd_dat_d0[7:0] = cheby_version_patch_i;
        rd_dat_d0[15:8] = cheby_version_minor_i;
        rd_dat_d0[31:16] = cheby_version_major_i;
      end
    default:
      rd_ack_d0 = rd_req;
    endcase
  end
endmodule
