// Do not edit.  Generated by cheby 1.7.dev0 using these options:
//  -i /home/akiel/trunk/pub/signalmesh/cheby/audio_regs.yaml --hdl verilog --gen-hdl /home/akiel/trunk/pub/signalmesh/modules/acm/acm_fpga/rtl/audio_regs.v
// Generated on Sat Jun 27 21:06:06 2026 by akiel



module audio
  (
    input   wire rst_n_i,
    input   wire clk_i,
    input   wire wb_cyc_i,
    input   wire wb_stb_i,
    input   wire [6:1] wb_adr_i,
    input   wire [1:0] wb_sel_i,
    input   wire wb_we_i,
    input   wire [15:0] wb_dat_i,
    output  wire wb_ack_o,
    output  wire wb_err_o,
    output  wire wb_rty_o,
    output  wire wb_stall_o,
    output  reg [15:0] wb_dat_o,

    // REG ctrl
    output  wire ctrl_enable_o,
    output  wire [1:0] ctrl_srate_o,

    // REG status
    input   wire [7:0] status_active_voices_i,

    // REG sample
    input   wire [15:0] sample_i,

    // REG dac
    input   wire [15:0] dac_i,

    // REG freq
    output  wire [31:0] voice_0_freq_o,

    // REG ctrl
    output  wire voice_0_ctrl_gate_o,
    output  wire [2:0] voice_0_ctrl_wave_o,
    output  wire [7:0] voice_0_ctrl_level_o,

    // REG freq
    output  wire [31:0] voice_1_freq_o,

    // REG ctrl
    output  wire voice_1_ctrl_gate_o,
    output  wire [2:0] voice_1_ctrl_wave_o,
    output  wire [7:0] voice_1_ctrl_level_o,

    // REG freq
    output  wire [31:0] voice_2_freq_o,

    // REG ctrl
    output  wire voice_2_ctrl_gate_o,
    output  wire [2:0] voice_2_ctrl_wave_o,
    output  wire [7:0] voice_2_ctrl_level_o,

    // REG freq
    output  wire [31:0] voice_3_freq_o,

    // REG ctrl
    output  wire voice_3_ctrl_gate_o,
    output  wire [2:0] voice_3_ctrl_wave_o,
    output  wire [7:0] voice_3_ctrl_level_o,

    // REG freq
    output  wire [31:0] voice_4_freq_o,

    // REG ctrl
    output  wire voice_4_ctrl_gate_o,
    output  wire [2:0] voice_4_ctrl_wave_o,
    output  wire [7:0] voice_4_ctrl_level_o,

    // REG freq
    output  wire [31:0] voice_5_freq_o,

    // REG ctrl
    output  wire voice_5_ctrl_gate_o,
    output  wire [2:0] voice_5_ctrl_wave_o,
    output  wire [7:0] voice_5_ctrl_level_o,

    // REG freq
    output  wire [31:0] voice_6_freq_o,

    // REG ctrl
    output  wire voice_6_ctrl_gate_o,
    output  wire [2:0] voice_6_ctrl_wave_o,
    output  wire [7:0] voice_6_ctrl_level_o,

    // REG freq
    output  wire [31:0] voice_7_freq_o,

    // REG ctrl
    output  wire voice_7_ctrl_gate_o,
    output  wire [2:0] voice_7_ctrl_wave_o,
    output  wire [7:0] voice_7_ctrl_level_o
  );
  wire rd_req_int;
  wire wr_req_int;
  reg rd_ack_int;
  reg wr_ack_int;
  wire wb_en;
  wire ack_int;
  reg wb_rip;
  reg wb_wip;
  reg ctrl_enable_reg;
  reg [1:0] ctrl_srate_reg;
  reg ctrl_wreq;
  wire ctrl_wack;
  reg [31:0] voice_0_freq_reg;
  reg [1:0] voice_0_freq_wreq;
  wire [1:0] voice_0_freq_wack;
  reg voice_0_ctrl_gate_reg;
  reg [2:0] voice_0_ctrl_wave_reg;
  reg [7:0] voice_0_ctrl_level_reg;
  reg voice_0_ctrl_wreq;
  wire voice_0_ctrl_wack;
  reg [31:0] voice_1_freq_reg;
  reg [1:0] voice_1_freq_wreq;
  wire [1:0] voice_1_freq_wack;
  reg voice_1_ctrl_gate_reg;
  reg [2:0] voice_1_ctrl_wave_reg;
  reg [7:0] voice_1_ctrl_level_reg;
  reg voice_1_ctrl_wreq;
  wire voice_1_ctrl_wack;
  reg [31:0] voice_2_freq_reg;
  reg [1:0] voice_2_freq_wreq;
  wire [1:0] voice_2_freq_wack;
  reg voice_2_ctrl_gate_reg;
  reg [2:0] voice_2_ctrl_wave_reg;
  reg [7:0] voice_2_ctrl_level_reg;
  reg voice_2_ctrl_wreq;
  wire voice_2_ctrl_wack;
  reg [31:0] voice_3_freq_reg;
  reg [1:0] voice_3_freq_wreq;
  wire [1:0] voice_3_freq_wack;
  reg voice_3_ctrl_gate_reg;
  reg [2:0] voice_3_ctrl_wave_reg;
  reg [7:0] voice_3_ctrl_level_reg;
  reg voice_3_ctrl_wreq;
  wire voice_3_ctrl_wack;
  reg [31:0] voice_4_freq_reg;
  reg [1:0] voice_4_freq_wreq;
  wire [1:0] voice_4_freq_wack;
  reg voice_4_ctrl_gate_reg;
  reg [2:0] voice_4_ctrl_wave_reg;
  reg [7:0] voice_4_ctrl_level_reg;
  reg voice_4_ctrl_wreq;
  wire voice_4_ctrl_wack;
  reg [31:0] voice_5_freq_reg;
  reg [1:0] voice_5_freq_wreq;
  wire [1:0] voice_5_freq_wack;
  reg voice_5_ctrl_gate_reg;
  reg [2:0] voice_5_ctrl_wave_reg;
  reg [7:0] voice_5_ctrl_level_reg;
  reg voice_5_ctrl_wreq;
  wire voice_5_ctrl_wack;
  reg [31:0] voice_6_freq_reg;
  reg [1:0] voice_6_freq_wreq;
  wire [1:0] voice_6_freq_wack;
  reg voice_6_ctrl_gate_reg;
  reg [2:0] voice_6_ctrl_wave_reg;
  reg [7:0] voice_6_ctrl_level_reg;
  reg voice_6_ctrl_wreq;
  wire voice_6_ctrl_wack;
  reg [31:0] voice_7_freq_reg;
  reg [1:0] voice_7_freq_wreq;
  wire [1:0] voice_7_freq_wack;
  reg voice_7_ctrl_gate_reg;
  reg [2:0] voice_7_ctrl_wave_reg;
  reg [7:0] voice_7_ctrl_level_reg;
  reg voice_7_ctrl_wreq;
  wire voice_7_ctrl_wack;
  reg rd_ack_d0;
  reg [15:0] rd_dat_d0;
  reg wr_req_d0;
  reg [6:1] wr_adr_d0;
  reg [15:0] wr_dat_d0;

  // WB decode signals
  always @(wb_sel_i)
  ;
  assign wb_en = wb_cyc_i & wb_stb_i;

  always @(posedge(clk_i))
  begin
    if (!rst_n_i)
      wb_rip <= 1'b0;
    else
      wb_rip <= (wb_rip | (wb_en & ~wb_we_i)) & ~rd_ack_int;
  end
  assign rd_req_int = (wb_en & ~wb_we_i) & ~wb_rip;

  always @(posedge(clk_i))
  begin
    if (!rst_n_i)
      wb_wip <= 1'b0;
    else
      wb_wip <= (wb_wip | (wb_en & wb_we_i)) & ~wr_ack_int;
  end
  assign wr_req_int = (wb_en & wb_we_i) & ~wb_wip;

  assign ack_int = rd_ack_int | wr_ack_int;
  assign wb_ack_o = ack_int;
  assign wb_stall_o = ~ack_int & wb_en;
  assign wb_rty_o = 1'b0;
  assign wb_err_o = 1'b0;

  // pipelining for wr-in+rd-out
  always @(posedge(clk_i))
  begin
    if (!rst_n_i)
      begin
        rd_ack_int <= 1'b0;
        wb_dat_o <= 16'b0000000000000000;
        wr_req_d0 <= 1'b0;
        wr_adr_d0 <= 6'b000000;
        wr_dat_d0 <= 16'b0000000000000000;
      end
    else
      begin
        rd_ack_int <= rd_ack_d0;
        wb_dat_o <= rd_dat_d0;
        wr_req_d0 <= wr_req_int;
        wr_adr_d0 <= wb_adr_i;
        wr_dat_d0 <= wb_dat_i;
      end
  end

  // Register ctrl
  assign ctrl_enable_o = ctrl_enable_reg;
  assign ctrl_srate_o = ctrl_srate_reg;
  assign ctrl_wack = ctrl_wreq;
  always @(posedge(clk_i))
  begin
    if (!rst_n_i)
      begin
        ctrl_enable_reg <= 1'b0;
        ctrl_srate_reg <= 2'b00;
      end
    else
      if (ctrl_wreq == 1'b1)
        begin
          ctrl_enable_reg <= wr_dat_d0[0];
          ctrl_srate_reg <= wr_dat_d0[2:1];
        end
  end

  // Register status

  // Register sample

  // Register dac

  // Register voice_0_freq
  assign voice_0_freq_o = voice_0_freq_reg;
  assign voice_0_freq_wack = voice_0_freq_wreq;
  always @(posedge(clk_i))
  begin
    if (!rst_n_i)
      voice_0_freq_reg <= 32'b00000000000000000000000000000000;
    else
      begin
        if (voice_0_freq_wreq[0] == 1'b1)
          voice_0_freq_reg[15:0] <= wr_dat_d0;
        if (voice_0_freq_wreq[1] == 1'b1)
          voice_0_freq_reg[31:16] <= wr_dat_d0;
      end
  end

  // Register voice_0_ctrl
  assign voice_0_ctrl_gate_o = voice_0_ctrl_gate_reg;
  assign voice_0_ctrl_wave_o = voice_0_ctrl_wave_reg;
  assign voice_0_ctrl_level_o = voice_0_ctrl_level_reg;
  assign voice_0_ctrl_wack = voice_0_ctrl_wreq;
  always @(posedge(clk_i))
  begin
    if (!rst_n_i)
      begin
        voice_0_ctrl_gate_reg <= 1'b0;
        voice_0_ctrl_wave_reg <= 3'b000;
        voice_0_ctrl_level_reg <= 8'b00000000;
      end
    else
      if (voice_0_ctrl_wreq == 1'b1)
        begin
          voice_0_ctrl_gate_reg <= wr_dat_d0[0];
          voice_0_ctrl_wave_reg <= wr_dat_d0[3:1];
          voice_0_ctrl_level_reg <= wr_dat_d0[15:8];
        end
  end

  // Register voice_1_freq
  assign voice_1_freq_o = voice_1_freq_reg;
  assign voice_1_freq_wack = voice_1_freq_wreq;
  always @(posedge(clk_i))
  begin
    if (!rst_n_i)
      voice_1_freq_reg <= 32'b00000000000000000000000000000000;
    else
      begin
        if (voice_1_freq_wreq[0] == 1'b1)
          voice_1_freq_reg[15:0] <= wr_dat_d0;
        if (voice_1_freq_wreq[1] == 1'b1)
          voice_1_freq_reg[31:16] <= wr_dat_d0;
      end
  end

  // Register voice_1_ctrl
  assign voice_1_ctrl_gate_o = voice_1_ctrl_gate_reg;
  assign voice_1_ctrl_wave_o = voice_1_ctrl_wave_reg;
  assign voice_1_ctrl_level_o = voice_1_ctrl_level_reg;
  assign voice_1_ctrl_wack = voice_1_ctrl_wreq;
  always @(posedge(clk_i))
  begin
    if (!rst_n_i)
      begin
        voice_1_ctrl_gate_reg <= 1'b0;
        voice_1_ctrl_wave_reg <= 3'b000;
        voice_1_ctrl_level_reg <= 8'b00000000;
      end
    else
      if (voice_1_ctrl_wreq == 1'b1)
        begin
          voice_1_ctrl_gate_reg <= wr_dat_d0[0];
          voice_1_ctrl_wave_reg <= wr_dat_d0[3:1];
          voice_1_ctrl_level_reg <= wr_dat_d0[15:8];
        end
  end

  // Register voice_2_freq
  assign voice_2_freq_o = voice_2_freq_reg;
  assign voice_2_freq_wack = voice_2_freq_wreq;
  always @(posedge(clk_i))
  begin
    if (!rst_n_i)
      voice_2_freq_reg <= 32'b00000000000000000000000000000000;
    else
      begin
        if (voice_2_freq_wreq[0] == 1'b1)
          voice_2_freq_reg[15:0] <= wr_dat_d0;
        if (voice_2_freq_wreq[1] == 1'b1)
          voice_2_freq_reg[31:16] <= wr_dat_d0;
      end
  end

  // Register voice_2_ctrl
  assign voice_2_ctrl_gate_o = voice_2_ctrl_gate_reg;
  assign voice_2_ctrl_wave_o = voice_2_ctrl_wave_reg;
  assign voice_2_ctrl_level_o = voice_2_ctrl_level_reg;
  assign voice_2_ctrl_wack = voice_2_ctrl_wreq;
  always @(posedge(clk_i))
  begin
    if (!rst_n_i)
      begin
        voice_2_ctrl_gate_reg <= 1'b0;
        voice_2_ctrl_wave_reg <= 3'b000;
        voice_2_ctrl_level_reg <= 8'b00000000;
      end
    else
      if (voice_2_ctrl_wreq == 1'b1)
        begin
          voice_2_ctrl_gate_reg <= wr_dat_d0[0];
          voice_2_ctrl_wave_reg <= wr_dat_d0[3:1];
          voice_2_ctrl_level_reg <= wr_dat_d0[15:8];
        end
  end

  // Register voice_3_freq
  assign voice_3_freq_o = voice_3_freq_reg;
  assign voice_3_freq_wack = voice_3_freq_wreq;
  always @(posedge(clk_i))
  begin
    if (!rst_n_i)
      voice_3_freq_reg <= 32'b00000000000000000000000000000000;
    else
      begin
        if (voice_3_freq_wreq[0] == 1'b1)
          voice_3_freq_reg[15:0] <= wr_dat_d0;
        if (voice_3_freq_wreq[1] == 1'b1)
          voice_3_freq_reg[31:16] <= wr_dat_d0;
      end
  end

  // Register voice_3_ctrl
  assign voice_3_ctrl_gate_o = voice_3_ctrl_gate_reg;
  assign voice_3_ctrl_wave_o = voice_3_ctrl_wave_reg;
  assign voice_3_ctrl_level_o = voice_3_ctrl_level_reg;
  assign voice_3_ctrl_wack = voice_3_ctrl_wreq;
  always @(posedge(clk_i))
  begin
    if (!rst_n_i)
      begin
        voice_3_ctrl_gate_reg <= 1'b0;
        voice_3_ctrl_wave_reg <= 3'b000;
        voice_3_ctrl_level_reg <= 8'b00000000;
      end
    else
      if (voice_3_ctrl_wreq == 1'b1)
        begin
          voice_3_ctrl_gate_reg <= wr_dat_d0[0];
          voice_3_ctrl_wave_reg <= wr_dat_d0[3:1];
          voice_3_ctrl_level_reg <= wr_dat_d0[15:8];
        end
  end

  // Register voice_4_freq
  assign voice_4_freq_o = voice_4_freq_reg;
  assign voice_4_freq_wack = voice_4_freq_wreq;
  always @(posedge(clk_i))
  begin
    if (!rst_n_i)
      voice_4_freq_reg <= 32'b00000000000000000000000000000000;
    else
      begin
        if (voice_4_freq_wreq[0] == 1'b1)
          voice_4_freq_reg[15:0] <= wr_dat_d0;
        if (voice_4_freq_wreq[1] == 1'b1)
          voice_4_freq_reg[31:16] <= wr_dat_d0;
      end
  end

  // Register voice_4_ctrl
  assign voice_4_ctrl_gate_o = voice_4_ctrl_gate_reg;
  assign voice_4_ctrl_wave_o = voice_4_ctrl_wave_reg;
  assign voice_4_ctrl_level_o = voice_4_ctrl_level_reg;
  assign voice_4_ctrl_wack = voice_4_ctrl_wreq;
  always @(posedge(clk_i))
  begin
    if (!rst_n_i)
      begin
        voice_4_ctrl_gate_reg <= 1'b0;
        voice_4_ctrl_wave_reg <= 3'b000;
        voice_4_ctrl_level_reg <= 8'b00000000;
      end
    else
      if (voice_4_ctrl_wreq == 1'b1)
        begin
          voice_4_ctrl_gate_reg <= wr_dat_d0[0];
          voice_4_ctrl_wave_reg <= wr_dat_d0[3:1];
          voice_4_ctrl_level_reg <= wr_dat_d0[15:8];
        end
  end

  // Register voice_5_freq
  assign voice_5_freq_o = voice_5_freq_reg;
  assign voice_5_freq_wack = voice_5_freq_wreq;
  always @(posedge(clk_i))
  begin
    if (!rst_n_i)
      voice_5_freq_reg <= 32'b00000000000000000000000000000000;
    else
      begin
        if (voice_5_freq_wreq[0] == 1'b1)
          voice_5_freq_reg[15:0] <= wr_dat_d0;
        if (voice_5_freq_wreq[1] == 1'b1)
          voice_5_freq_reg[31:16] <= wr_dat_d0;
      end
  end

  // Register voice_5_ctrl
  assign voice_5_ctrl_gate_o = voice_5_ctrl_gate_reg;
  assign voice_5_ctrl_wave_o = voice_5_ctrl_wave_reg;
  assign voice_5_ctrl_level_o = voice_5_ctrl_level_reg;
  assign voice_5_ctrl_wack = voice_5_ctrl_wreq;
  always @(posedge(clk_i))
  begin
    if (!rst_n_i)
      begin
        voice_5_ctrl_gate_reg <= 1'b0;
        voice_5_ctrl_wave_reg <= 3'b000;
        voice_5_ctrl_level_reg <= 8'b00000000;
      end
    else
      if (voice_5_ctrl_wreq == 1'b1)
        begin
          voice_5_ctrl_gate_reg <= wr_dat_d0[0];
          voice_5_ctrl_wave_reg <= wr_dat_d0[3:1];
          voice_5_ctrl_level_reg <= wr_dat_d0[15:8];
        end
  end

  // Register voice_6_freq
  assign voice_6_freq_o = voice_6_freq_reg;
  assign voice_6_freq_wack = voice_6_freq_wreq;
  always @(posedge(clk_i))
  begin
    if (!rst_n_i)
      voice_6_freq_reg <= 32'b00000000000000000000000000000000;
    else
      begin
        if (voice_6_freq_wreq[0] == 1'b1)
          voice_6_freq_reg[15:0] <= wr_dat_d0;
        if (voice_6_freq_wreq[1] == 1'b1)
          voice_6_freq_reg[31:16] <= wr_dat_d0;
      end
  end

  // Register voice_6_ctrl
  assign voice_6_ctrl_gate_o = voice_6_ctrl_gate_reg;
  assign voice_6_ctrl_wave_o = voice_6_ctrl_wave_reg;
  assign voice_6_ctrl_level_o = voice_6_ctrl_level_reg;
  assign voice_6_ctrl_wack = voice_6_ctrl_wreq;
  always @(posedge(clk_i))
  begin
    if (!rst_n_i)
      begin
        voice_6_ctrl_gate_reg <= 1'b0;
        voice_6_ctrl_wave_reg <= 3'b000;
        voice_6_ctrl_level_reg <= 8'b00000000;
      end
    else
      if (voice_6_ctrl_wreq == 1'b1)
        begin
          voice_6_ctrl_gate_reg <= wr_dat_d0[0];
          voice_6_ctrl_wave_reg <= wr_dat_d0[3:1];
          voice_6_ctrl_level_reg <= wr_dat_d0[15:8];
        end
  end

  // Register voice_7_freq
  assign voice_7_freq_o = voice_7_freq_reg;
  assign voice_7_freq_wack = voice_7_freq_wreq;
  always @(posedge(clk_i))
  begin
    if (!rst_n_i)
      voice_7_freq_reg <= 32'b00000000000000000000000000000000;
    else
      begin
        if (voice_7_freq_wreq[0] == 1'b1)
          voice_7_freq_reg[15:0] <= wr_dat_d0;
        if (voice_7_freq_wreq[1] == 1'b1)
          voice_7_freq_reg[31:16] <= wr_dat_d0;
      end
  end

  // Register voice_7_ctrl
  assign voice_7_ctrl_gate_o = voice_7_ctrl_gate_reg;
  assign voice_7_ctrl_wave_o = voice_7_ctrl_wave_reg;
  assign voice_7_ctrl_level_o = voice_7_ctrl_level_reg;
  assign voice_7_ctrl_wack = voice_7_ctrl_wreq;
  always @(posedge(clk_i))
  begin
    if (!rst_n_i)
      begin
        voice_7_ctrl_gate_reg <= 1'b0;
        voice_7_ctrl_wave_reg <= 3'b000;
        voice_7_ctrl_level_reg <= 8'b00000000;
      end
    else
      if (voice_7_ctrl_wreq == 1'b1)
        begin
          voice_7_ctrl_gate_reg <= wr_dat_d0[0];
          voice_7_ctrl_wave_reg <= wr_dat_d0[3:1];
          voice_7_ctrl_level_reg <= wr_dat_d0[15:8];
        end
  end

  // Process for write requests.
  always @(wr_adr_d0, wr_req_d0, ctrl_wack, voice_0_freq_wack, voice_0_ctrl_wack, voice_1_freq_wack, voice_1_ctrl_wack, voice_2_freq_wack, voice_2_ctrl_wack, voice_3_freq_wack, voice_3_ctrl_wack, voice_4_freq_wack, voice_4_ctrl_wack, voice_5_freq_wack, voice_5_ctrl_wack, voice_6_freq_wack, voice_6_ctrl_wack, voice_7_freq_wack, voice_7_ctrl_wack)
  begin
    ctrl_wreq = 1'b0;
    voice_0_freq_wreq = 2'b0;
    voice_0_ctrl_wreq = 1'b0;
    voice_1_freq_wreq = 2'b0;
    voice_1_ctrl_wreq = 1'b0;
    voice_2_freq_wreq = 2'b0;
    voice_2_ctrl_wreq = 1'b0;
    voice_3_freq_wreq = 2'b0;
    voice_3_ctrl_wreq = 1'b0;
    voice_4_freq_wreq = 2'b0;
    voice_4_ctrl_wreq = 1'b0;
    voice_5_freq_wreq = 2'b0;
    voice_5_ctrl_wreq = 1'b0;
    voice_6_freq_wreq = 2'b0;
    voice_6_ctrl_wreq = 1'b0;
    voice_7_freq_wreq = 2'b0;
    voice_7_ctrl_wreq = 1'b0;
    case (wr_adr_d0[6:2])
    5'b00000:
      case (wr_adr_d0[1:1])
      1'b0:
        begin
          // Reg ctrl
          ctrl_wreq = wr_req_d0;
          wr_ack_int = ctrl_wack;
        end
      1'b1:
        // Reg status
        wr_ack_int = wr_req_d0;
      default:
        wr_ack_int = wr_req_d0;
      endcase
    5'b00001:
      case (wr_adr_d0[1:1])
      1'b0:
        // Reg sample
        wr_ack_int = wr_req_d0;
      1'b1:
        // Reg dac
        wr_ack_int = wr_req_d0;
      default:
        wr_ack_int = wr_req_d0;
      endcase
    5'b10000:
      case (wr_adr_d0[1:1])
      1'b0:
        begin
          // Reg voice_0_freq
          voice_0_freq_wreq[1] = wr_req_d0;
          wr_ack_int = voice_0_freq_wack[1];
        end
      1'b1:
        begin
          // Reg voice_0_freq
          voice_0_freq_wreq[0] = wr_req_d0;
          wr_ack_int = voice_0_freq_wack[0];
        end
      default:
        wr_ack_int = wr_req_d0;
      endcase
    5'b10001:
      case (wr_adr_d0[1:1])
      1'b0:
        begin
          // Reg voice_0_ctrl
          voice_0_ctrl_wreq = wr_req_d0;
          wr_ack_int = voice_0_ctrl_wack;
        end
      default:
        wr_ack_int = wr_req_d0;
      endcase
    5'b10010:
      case (wr_adr_d0[1:1])
      1'b0:
        begin
          // Reg voice_1_freq
          voice_1_freq_wreq[1] = wr_req_d0;
          wr_ack_int = voice_1_freq_wack[1];
        end
      1'b1:
        begin
          // Reg voice_1_freq
          voice_1_freq_wreq[0] = wr_req_d0;
          wr_ack_int = voice_1_freq_wack[0];
        end
      default:
        wr_ack_int = wr_req_d0;
      endcase
    5'b10011:
      case (wr_adr_d0[1:1])
      1'b0:
        begin
          // Reg voice_1_ctrl
          voice_1_ctrl_wreq = wr_req_d0;
          wr_ack_int = voice_1_ctrl_wack;
        end
      default:
        wr_ack_int = wr_req_d0;
      endcase
    5'b10100:
      case (wr_adr_d0[1:1])
      1'b0:
        begin
          // Reg voice_2_freq
          voice_2_freq_wreq[1] = wr_req_d0;
          wr_ack_int = voice_2_freq_wack[1];
        end
      1'b1:
        begin
          // Reg voice_2_freq
          voice_2_freq_wreq[0] = wr_req_d0;
          wr_ack_int = voice_2_freq_wack[0];
        end
      default:
        wr_ack_int = wr_req_d0;
      endcase
    5'b10101:
      case (wr_adr_d0[1:1])
      1'b0:
        begin
          // Reg voice_2_ctrl
          voice_2_ctrl_wreq = wr_req_d0;
          wr_ack_int = voice_2_ctrl_wack;
        end
      default:
        wr_ack_int = wr_req_d0;
      endcase
    5'b10110:
      case (wr_adr_d0[1:1])
      1'b0:
        begin
          // Reg voice_3_freq
          voice_3_freq_wreq[1] = wr_req_d0;
          wr_ack_int = voice_3_freq_wack[1];
        end
      1'b1:
        begin
          // Reg voice_3_freq
          voice_3_freq_wreq[0] = wr_req_d0;
          wr_ack_int = voice_3_freq_wack[0];
        end
      default:
        wr_ack_int = wr_req_d0;
      endcase
    5'b10111:
      case (wr_adr_d0[1:1])
      1'b0:
        begin
          // Reg voice_3_ctrl
          voice_3_ctrl_wreq = wr_req_d0;
          wr_ack_int = voice_3_ctrl_wack;
        end
      default:
        wr_ack_int = wr_req_d0;
      endcase
    5'b11000:
      case (wr_adr_d0[1:1])
      1'b0:
        begin
          // Reg voice_4_freq
          voice_4_freq_wreq[1] = wr_req_d0;
          wr_ack_int = voice_4_freq_wack[1];
        end
      1'b1:
        begin
          // Reg voice_4_freq
          voice_4_freq_wreq[0] = wr_req_d0;
          wr_ack_int = voice_4_freq_wack[0];
        end
      default:
        wr_ack_int = wr_req_d0;
      endcase
    5'b11001:
      case (wr_adr_d0[1:1])
      1'b0:
        begin
          // Reg voice_4_ctrl
          voice_4_ctrl_wreq = wr_req_d0;
          wr_ack_int = voice_4_ctrl_wack;
        end
      default:
        wr_ack_int = wr_req_d0;
      endcase
    5'b11010:
      case (wr_adr_d0[1:1])
      1'b0:
        begin
          // Reg voice_5_freq
          voice_5_freq_wreq[1] = wr_req_d0;
          wr_ack_int = voice_5_freq_wack[1];
        end
      1'b1:
        begin
          // Reg voice_5_freq
          voice_5_freq_wreq[0] = wr_req_d0;
          wr_ack_int = voice_5_freq_wack[0];
        end
      default:
        wr_ack_int = wr_req_d0;
      endcase
    5'b11011:
      case (wr_adr_d0[1:1])
      1'b0:
        begin
          // Reg voice_5_ctrl
          voice_5_ctrl_wreq = wr_req_d0;
          wr_ack_int = voice_5_ctrl_wack;
        end
      default:
        wr_ack_int = wr_req_d0;
      endcase
    5'b11100:
      case (wr_adr_d0[1:1])
      1'b0:
        begin
          // Reg voice_6_freq
          voice_6_freq_wreq[1] = wr_req_d0;
          wr_ack_int = voice_6_freq_wack[1];
        end
      1'b1:
        begin
          // Reg voice_6_freq
          voice_6_freq_wreq[0] = wr_req_d0;
          wr_ack_int = voice_6_freq_wack[0];
        end
      default:
        wr_ack_int = wr_req_d0;
      endcase
    5'b11101:
      case (wr_adr_d0[1:1])
      1'b0:
        begin
          // Reg voice_6_ctrl
          voice_6_ctrl_wreq = wr_req_d0;
          wr_ack_int = voice_6_ctrl_wack;
        end
      default:
        wr_ack_int = wr_req_d0;
      endcase
    5'b11110:
      case (wr_adr_d0[1:1])
      1'b0:
        begin
          // Reg voice_7_freq
          voice_7_freq_wreq[1] = wr_req_d0;
          wr_ack_int = voice_7_freq_wack[1];
        end
      1'b1:
        begin
          // Reg voice_7_freq
          voice_7_freq_wreq[0] = wr_req_d0;
          wr_ack_int = voice_7_freq_wack[0];
        end
      default:
        wr_ack_int = wr_req_d0;
      endcase
    5'b11111:
      case (wr_adr_d0[1:1])
      1'b0:
        begin
          // Reg voice_7_ctrl
          voice_7_ctrl_wreq = wr_req_d0;
          wr_ack_int = voice_7_ctrl_wack;
        end
      default:
        wr_ack_int = wr_req_d0;
      endcase
    default:
      wr_ack_int = wr_req_d0;
    endcase
  end

  // Process for read requests.
  always @(wb_adr_i, rd_req_int, ctrl_enable_reg, ctrl_srate_reg, status_active_voices_i, sample_i, dac_i, voice_0_freq_reg, voice_0_ctrl_gate_reg, voice_0_ctrl_wave_reg, voice_0_ctrl_level_reg, voice_1_freq_reg, voice_1_ctrl_gate_reg, voice_1_ctrl_wave_reg, voice_1_ctrl_level_reg, voice_2_freq_reg, voice_2_ctrl_gate_reg, voice_2_ctrl_wave_reg, voice_2_ctrl_level_reg, voice_3_freq_reg, voice_3_ctrl_gate_reg, voice_3_ctrl_wave_reg, voice_3_ctrl_level_reg, voice_4_freq_reg, voice_4_ctrl_gate_reg, voice_4_ctrl_wave_reg, voice_4_ctrl_level_reg, voice_5_freq_reg, voice_5_ctrl_gate_reg, voice_5_ctrl_wave_reg, voice_5_ctrl_level_reg, voice_6_freq_reg, voice_6_ctrl_gate_reg, voice_6_ctrl_wave_reg, voice_6_ctrl_level_reg, voice_7_freq_reg, voice_7_ctrl_gate_reg, voice_7_ctrl_wave_reg, voice_7_ctrl_level_reg)
  begin
    // By default ack read requests
    rd_dat_d0 = {16{1'bx}};
    case (wb_adr_i[6:2])
    5'b00000:
      case (wb_adr_i[1:1])
      1'b0:
        begin
          // Reg ctrl
          rd_ack_d0 = rd_req_int;
          rd_dat_d0[0] = ctrl_enable_reg;
          rd_dat_d0[2:1] = ctrl_srate_reg;
          rd_dat_d0[15:3] = 13'b0;
        end
      1'b1:
        begin
          // Reg status
          rd_ack_d0 = rd_req_int;
          rd_dat_d0[7:0] = status_active_voices_i;
          rd_dat_d0[15:8] = 8'b0;
        end
      default:
        rd_ack_d0 = rd_req_int;
      endcase
    5'b00001:
      case (wb_adr_i[1:1])
      1'b0:
        begin
          // Reg sample
          rd_ack_d0 = rd_req_int;
          rd_dat_d0 = sample_i;
        end
      1'b1:
        begin
          // Reg dac
          rd_ack_d0 = rd_req_int;
          rd_dat_d0 = dac_i;
        end
      default:
        rd_ack_d0 = rd_req_int;
      endcase
    5'b10000:
      case (wb_adr_i[1:1])
      1'b0:
        begin
          // Reg voice_0_freq
          rd_ack_d0 = rd_req_int;
          rd_dat_d0 = voice_0_freq_reg[31:16];
        end
      1'b1:
        begin
          // Reg voice_0_freq
          rd_ack_d0 = rd_req_int;
          rd_dat_d0 = voice_0_freq_reg[15:0];
        end
      default:
        rd_ack_d0 = rd_req_int;
      endcase
    5'b10001:
      case (wb_adr_i[1:1])
      1'b0:
        begin
          // Reg voice_0_ctrl
          rd_ack_d0 = rd_req_int;
          rd_dat_d0[0] = voice_0_ctrl_gate_reg;
          rd_dat_d0[3:1] = voice_0_ctrl_wave_reg;
          rd_dat_d0[7:4] = 4'b0;
          rd_dat_d0[15:8] = voice_0_ctrl_level_reg;
        end
      default:
        rd_ack_d0 = rd_req_int;
      endcase
    5'b10010:
      case (wb_adr_i[1:1])
      1'b0:
        begin
          // Reg voice_1_freq
          rd_ack_d0 = rd_req_int;
          rd_dat_d0 = voice_1_freq_reg[31:16];
        end
      1'b1:
        begin
          // Reg voice_1_freq
          rd_ack_d0 = rd_req_int;
          rd_dat_d0 = voice_1_freq_reg[15:0];
        end
      default:
        rd_ack_d0 = rd_req_int;
      endcase
    5'b10011:
      case (wb_adr_i[1:1])
      1'b0:
        begin
          // Reg voice_1_ctrl
          rd_ack_d0 = rd_req_int;
          rd_dat_d0[0] = voice_1_ctrl_gate_reg;
          rd_dat_d0[3:1] = voice_1_ctrl_wave_reg;
          rd_dat_d0[7:4] = 4'b0;
          rd_dat_d0[15:8] = voice_1_ctrl_level_reg;
        end
      default:
        rd_ack_d0 = rd_req_int;
      endcase
    5'b10100:
      case (wb_adr_i[1:1])
      1'b0:
        begin
          // Reg voice_2_freq
          rd_ack_d0 = rd_req_int;
          rd_dat_d0 = voice_2_freq_reg[31:16];
        end
      1'b1:
        begin
          // Reg voice_2_freq
          rd_ack_d0 = rd_req_int;
          rd_dat_d0 = voice_2_freq_reg[15:0];
        end
      default:
        rd_ack_d0 = rd_req_int;
      endcase
    5'b10101:
      case (wb_adr_i[1:1])
      1'b0:
        begin
          // Reg voice_2_ctrl
          rd_ack_d0 = rd_req_int;
          rd_dat_d0[0] = voice_2_ctrl_gate_reg;
          rd_dat_d0[3:1] = voice_2_ctrl_wave_reg;
          rd_dat_d0[7:4] = 4'b0;
          rd_dat_d0[15:8] = voice_2_ctrl_level_reg;
        end
      default:
        rd_ack_d0 = rd_req_int;
      endcase
    5'b10110:
      case (wb_adr_i[1:1])
      1'b0:
        begin
          // Reg voice_3_freq
          rd_ack_d0 = rd_req_int;
          rd_dat_d0 = voice_3_freq_reg[31:16];
        end
      1'b1:
        begin
          // Reg voice_3_freq
          rd_ack_d0 = rd_req_int;
          rd_dat_d0 = voice_3_freq_reg[15:0];
        end
      default:
        rd_ack_d0 = rd_req_int;
      endcase
    5'b10111:
      case (wb_adr_i[1:1])
      1'b0:
        begin
          // Reg voice_3_ctrl
          rd_ack_d0 = rd_req_int;
          rd_dat_d0[0] = voice_3_ctrl_gate_reg;
          rd_dat_d0[3:1] = voice_3_ctrl_wave_reg;
          rd_dat_d0[7:4] = 4'b0;
          rd_dat_d0[15:8] = voice_3_ctrl_level_reg;
        end
      default:
        rd_ack_d0 = rd_req_int;
      endcase
    5'b11000:
      case (wb_adr_i[1:1])
      1'b0:
        begin
          // Reg voice_4_freq
          rd_ack_d0 = rd_req_int;
          rd_dat_d0 = voice_4_freq_reg[31:16];
        end
      1'b1:
        begin
          // Reg voice_4_freq
          rd_ack_d0 = rd_req_int;
          rd_dat_d0 = voice_4_freq_reg[15:0];
        end
      default:
        rd_ack_d0 = rd_req_int;
      endcase
    5'b11001:
      case (wb_adr_i[1:1])
      1'b0:
        begin
          // Reg voice_4_ctrl
          rd_ack_d0 = rd_req_int;
          rd_dat_d0[0] = voice_4_ctrl_gate_reg;
          rd_dat_d0[3:1] = voice_4_ctrl_wave_reg;
          rd_dat_d0[7:4] = 4'b0;
          rd_dat_d0[15:8] = voice_4_ctrl_level_reg;
        end
      default:
        rd_ack_d0 = rd_req_int;
      endcase
    5'b11010:
      case (wb_adr_i[1:1])
      1'b0:
        begin
          // Reg voice_5_freq
          rd_ack_d0 = rd_req_int;
          rd_dat_d0 = voice_5_freq_reg[31:16];
        end
      1'b1:
        begin
          // Reg voice_5_freq
          rd_ack_d0 = rd_req_int;
          rd_dat_d0 = voice_5_freq_reg[15:0];
        end
      default:
        rd_ack_d0 = rd_req_int;
      endcase
    5'b11011:
      case (wb_adr_i[1:1])
      1'b0:
        begin
          // Reg voice_5_ctrl
          rd_ack_d0 = rd_req_int;
          rd_dat_d0[0] = voice_5_ctrl_gate_reg;
          rd_dat_d0[3:1] = voice_5_ctrl_wave_reg;
          rd_dat_d0[7:4] = 4'b0;
          rd_dat_d0[15:8] = voice_5_ctrl_level_reg;
        end
      default:
        rd_ack_d0 = rd_req_int;
      endcase
    5'b11100:
      case (wb_adr_i[1:1])
      1'b0:
        begin
          // Reg voice_6_freq
          rd_ack_d0 = rd_req_int;
          rd_dat_d0 = voice_6_freq_reg[31:16];
        end
      1'b1:
        begin
          // Reg voice_6_freq
          rd_ack_d0 = rd_req_int;
          rd_dat_d0 = voice_6_freq_reg[15:0];
        end
      default:
        rd_ack_d0 = rd_req_int;
      endcase
    5'b11101:
      case (wb_adr_i[1:1])
      1'b0:
        begin
          // Reg voice_6_ctrl
          rd_ack_d0 = rd_req_int;
          rd_dat_d0[0] = voice_6_ctrl_gate_reg;
          rd_dat_d0[3:1] = voice_6_ctrl_wave_reg;
          rd_dat_d0[7:4] = 4'b0;
          rd_dat_d0[15:8] = voice_6_ctrl_level_reg;
        end
      default:
        rd_ack_d0 = rd_req_int;
      endcase
    5'b11110:
      case (wb_adr_i[1:1])
      1'b0:
        begin
          // Reg voice_7_freq
          rd_ack_d0 = rd_req_int;
          rd_dat_d0 = voice_7_freq_reg[31:16];
        end
      1'b1:
        begin
          // Reg voice_7_freq
          rd_ack_d0 = rd_req_int;
          rd_dat_d0 = voice_7_freq_reg[15:0];
        end
      default:
        rd_ack_d0 = rd_req_int;
      endcase
    5'b11111:
      case (wb_adr_i[1:1])
      1'b0:
        begin
          // Reg voice_7_ctrl
          rd_ack_d0 = rd_req_int;
          rd_dat_d0[0] = voice_7_ctrl_gate_reg;
          rd_dat_d0[3:1] = voice_7_ctrl_wave_reg;
          rd_dat_d0[7:4] = 4'b0;
          rd_dat_d0[15:8] = voice_7_ctrl_level_reg;
        end
      default:
        rd_ack_d0 = rd_req_int;
      endcase
    default:
      rd_ack_d0 = rd_req_int;
    endcase
  end
endmodule
