// Do not edit.  Generated by cheby 1.7.dev0 using these options:
//  -i /home/akiel/trunk/pub/signalmesh/cheby/core_regs.yaml --hdl verilog --gen-hdl /home/akiel/trunk/pub/signalmesh/modules/acm/acm_fpga/rtl/core_regs.v
// Generated on Sat Jun 27 16:31:39 2026 by akiel



module core
  (
    input   wire rst_n_i,
    input   wire clk_i,
    input   wire wb_cyc_i,
    input   wire wb_stb_i,
    input   wire [2:1] wb_adr_i,
    input   wire [1:0] wb_sel_i,
    input   wire wb_we_i,
    input   wire [15:0] wb_dat_i,
    output  wire wb_ack_o,
    output  wire wb_err_o,
    output  wire wb_rty_o,
    output  wire wb_stall_o,
    output  reg [15:0] wb_dat_o,

    // REG magic
    input   wire [15:0] magic_i,

    // REG fpga_id
    input   wire [15:0] fpga_id_i,

    // REG scratch
    output  wire [15:0] scratch_o,

    // REG version
    input   wire [15:0] version_i
  );
  wire rd_req_int;
  wire wr_req_int;
  reg rd_ack_int;
  reg wr_ack_int;
  wire wb_en;
  wire ack_int;
  reg wb_rip;
  reg wb_wip;
  reg [15:0] scratch_reg;
  reg scratch_wreq;
  wire scratch_wack;
  reg rd_ack_d0;
  reg [15:0] rd_dat_d0;
  reg wr_req_d0;
  reg [2:1] wr_adr_d0;
  reg [15:0] wr_dat_d0;

  // WB decode signals
  always @(wb_sel_i)
  ;
  assign wb_en = wb_cyc_i & wb_stb_i;

  always @(posedge(clk_i))
  begin
    if (!rst_n_i)
      wb_rip <= 1'b0;
    else
      wb_rip <= (wb_rip | (wb_en & ~wb_we_i)) & ~rd_ack_int;
  end
  assign rd_req_int = (wb_en & ~wb_we_i) & ~wb_rip;

  always @(posedge(clk_i))
  begin
    if (!rst_n_i)
      wb_wip <= 1'b0;
    else
      wb_wip <= (wb_wip | (wb_en & wb_we_i)) & ~wr_ack_int;
  end
  assign wr_req_int = (wb_en & wb_we_i) & ~wb_wip;

  assign ack_int = rd_ack_int | wr_ack_int;
  assign wb_ack_o = ack_int;
  assign wb_stall_o = ~ack_int & wb_en;
  assign wb_rty_o = 1'b0;
  assign wb_err_o = 1'b0;

  // pipelining for wr-in+rd-out
  always @(posedge(clk_i))
  begin
    if (!rst_n_i)
      begin
        rd_ack_int <= 1'b0;
        wb_dat_o <= 16'b0000000000000000;
        wr_req_d0 <= 1'b0;
        wr_adr_d0 <= 2'b00;
        wr_dat_d0 <= 16'b0000000000000000;
      end
    else
      begin
        rd_ack_int <= rd_ack_d0;
        wb_dat_o <= rd_dat_d0;
        wr_req_d0 <= wr_req_int;
        wr_adr_d0 <= wb_adr_i;
        wr_dat_d0 <= wb_dat_i;
      end
  end

  // Register magic

  // Register fpga_id

  // Register scratch
  assign scratch_o = scratch_reg;
  assign scratch_wack = scratch_wreq;
  always @(posedge(clk_i))
  begin
    if (!rst_n_i)
      scratch_reg <= 16'b0000000000000000;
    else
      if (scratch_wreq == 1'b1)
        scratch_reg <= wr_dat_d0;
  end

  // Register version

  // Process for write requests.
  always @(wr_adr_d0, wr_req_d0, scratch_wack)
  begin
    scratch_wreq = 1'b0;
    case (wr_adr_d0[2:1])
    2'b00:
      // Reg magic
      wr_ack_int = wr_req_d0;
    2'b01:
      // Reg fpga_id
      wr_ack_int = wr_req_d0;
    2'b10:
      begin
        // Reg scratch
        scratch_wreq = wr_req_d0;
        wr_ack_int = scratch_wack;
      end
    2'b11:
      // Reg version
      wr_ack_int = wr_req_d0;
    default:
      wr_ack_int = wr_req_d0;
    endcase
  end

  // Process for read requests.
  always @(wb_adr_i, rd_req_int, magic_i, fpga_id_i, scratch_reg, version_i)
  begin
    // By default ack read requests
    rd_dat_d0 = {16{1'bx}};
    case (wb_adr_i[2:1])
    2'b00:
      begin
        // Reg magic
        rd_ack_d0 = rd_req_int;
        rd_dat_d0 = magic_i;
      end
    2'b01:
      begin
        // Reg fpga_id
        rd_ack_d0 = rd_req_int;
        rd_dat_d0 = fpga_id_i;
      end
    2'b10:
      begin
        // Reg scratch
        rd_ack_d0 = rd_req_int;
        rd_dat_d0 = scratch_reg;
      end
    2'b11:
      begin
        // Reg version
        rd_ack_d0 = rd_req_int;
        rd_dat_d0 = version_i;
      end
    default:
      rd_ack_d0 = rd_req_int;
    endcase
  end
endmodule
